### ISSUE TITLE
fix gcc warning messages

### ISSUE THREAD

**Issue by blshkv** [gat3way/hashkill#4]
I've compiled 0.3.0 version using gcc version 4.5.4 (Gentoo Hardened 4.5.4 p1.0, pie-0.4.7)
It shows a lot of different warning messages. See the link below:
http://pastebin.com/2kcH3RsA

The most critial are "overflow destination buffer". Please also see QA Notices.

**Comment by gat3way** [comment]
I am surprised it succeeded to build using gcc-4.5 at all. It is the version that introduced XOP intrinsics support, but it was broken (at least for me) and since my development system has a bulldozer, it was unusable. The second (bigger) issue is that -fwhole-program does not work on gcc <4.6.0. I never succeeded to build using it, it gave me weird compilation errors about some symbols missing and stuff. On the other hand, fwhole-program brings significant performance gain and decreased code size, so I prefer using it instead of not using it. 

Is using gcc-4.6 an option for you? I highly recommend using it as it just works. gcc-4.7 of course also works, yet for some reason it generates slower code than 4.6.

**Comment by blshkv** [comment]
It's recommended to use one version of a compiler under Gentoo so it's not really an option for many people right now. As an experiment, I have recompiled the tool using gcc-4.6.3, the build warnings are still there. Here is the updated output:
http://pastebin.com/2GDJhdEW

the size has not changed much:
9474664 bytes (gcc-4.5.4)
9364728 bytes (gcc-4.6.3)

As for the speed, LTO patches are still experemental and the results are also quite ambiguous:
http://www.phoronix.com/scan.php?page=article&item=gcc_471_lto&num=1

**Comment by gat3way** [comment]
Warnings were finally identified to be present only when compiling with -fstack-protector and -fmudflap (which were likely passed when building under Gentoo Hardened). There were indeed 4 instances where sprintf/memcpy over stack-allocated buffers were controversial, 3 of them were relatively innocent, the fourth one was quite dangerous indeed.

Fix was commited to address the problem:
https://github.com/gat3way/hashkill/commit/30f45b2f1817d20799c7ac610012a26e6db51e43

Closing this issue.

**Comment by blshkv** [comment]
Since we are here, could you also fix the "QA Notice: Files built without respecting LDFLAGS have been detected" warning? The fix would be something like this:
Makefile:
-$(CC) $(CFLAGS) 
+$(CC) $(CFLAGS) $(LDFLAGS)
